package dao.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChatGroupUserCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public ChatGroupUserCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdIsNull() {
            addCriterion("chat_group_id is null");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdIsNotNull() {
            addCriterion("chat_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdEqualTo(String value) {
            addCriterion("chat_group_id =", value, "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdNotEqualTo(String value) {
            addCriterion("chat_group_id <>", value, "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdGreaterThan(String value) {
            addCriterion("chat_group_id >", value, "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("chat_group_id >=", value, "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdLessThan(String value) {
            addCriterion("chat_group_id <", value, "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdLessThanOrEqualTo(String value) {
            addCriterion("chat_group_id <=", value, "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdLike(String value) {
            addCriterion("chat_group_id like", value, "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdNotLike(String value) {
            addCriterion("chat_group_id not like", value, "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdIn(List<String> values) {
            addCriterion("chat_group_id in", values, "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdNotIn(List<String> values) {
            addCriterion("chat_group_id not in", values, "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdBetween(String value1, String value2) {
            addCriterion("chat_group_id between", value1, value2, "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdNotBetween(String value1, String value2) {
            addCriterion("chat_group_id not between", value1, value2, "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameIsNull() {
            addCriterion("chat_group_user_real_name is null");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameIsNotNull() {
            addCriterion("chat_group_user_real_name is not null");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameEqualTo(String value) {
            addCriterion("chat_group_user_real_name =", value, "chatGroupUserRealName");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameNotEqualTo(String value) {
            addCriterion("chat_group_user_real_name <>", value, "chatGroupUserRealName");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameGreaterThan(String value) {
            addCriterion("chat_group_user_real_name >", value, "chatGroupUserRealName");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("chat_group_user_real_name >=", value, "chatGroupUserRealName");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameLessThan(String value) {
            addCriterion("chat_group_user_real_name <", value, "chatGroupUserRealName");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameLessThanOrEqualTo(String value) {
            addCriterion("chat_group_user_real_name <=", value, "chatGroupUserRealName");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameLike(String value) {
            addCriterion("chat_group_user_real_name like", value, "chatGroupUserRealName");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameNotLike(String value) {
            addCriterion("chat_group_user_real_name not like", value, "chatGroupUserRealName");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameIn(List<String> values) {
            addCriterion("chat_group_user_real_name in", values, "chatGroupUserRealName");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameNotIn(List<String> values) {
            addCriterion("chat_group_user_real_name not in", values, "chatGroupUserRealName");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameBetween(String value1, String value2) {
            addCriterion("chat_group_user_real_name between", value1, value2, "chatGroupUserRealName");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameNotBetween(String value1, String value2) {
            addCriterion("chat_group_user_real_name not between", value1, value2, "chatGroupUserRealName");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRoleIsNull() {
            addCriterion("chat_group_user_role is null");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRoleIsNotNull() {
            addCriterion("chat_group_user_role is not null");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRoleEqualTo(Byte value) {
            addCriterion("chat_group_user_role =", value, "chatGroupUserRole");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRoleNotEqualTo(Byte value) {
            addCriterion("chat_group_user_role <>", value, "chatGroupUserRole");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRoleGreaterThan(Byte value) {
            addCriterion("chat_group_user_role >", value, "chatGroupUserRole");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRoleGreaterThanOrEqualTo(Byte value) {
            addCriterion("chat_group_user_role >=", value, "chatGroupUserRole");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRoleLessThan(Byte value) {
            addCriterion("chat_group_user_role <", value, "chatGroupUserRole");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRoleLessThanOrEqualTo(Byte value) {
            addCriterion("chat_group_user_role <=", value, "chatGroupUserRole");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRoleIn(List<Byte> values) {
            addCriterion("chat_group_user_role in", values, "chatGroupUserRole");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRoleNotIn(List<Byte> values) {
            addCriterion("chat_group_user_role not in", values, "chatGroupUserRole");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRoleBetween(Byte value1, Byte value2) {
            addCriterion("chat_group_user_role between", value1, value2, "chatGroupUserRole");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRoleNotBetween(Byte value1, Byte value2) {
            addCriterion("chat_group_user_role not between", value1, value2, "chatGroupUserRole");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserUpdateTimeIsNull() {
            addCriterion("chat_group_user_update_time is null");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserUpdateTimeIsNotNull() {
            addCriterion("chat_group_user_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserUpdateTimeEqualTo(Date value) {
            addCriterion("chat_group_user_update_time =", value, "chatGroupUserUpdateTime");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserUpdateTimeNotEqualTo(Date value) {
            addCriterion("chat_group_user_update_time <>", value, "chatGroupUserUpdateTime");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserUpdateTimeGreaterThan(Date value) {
            addCriterion("chat_group_user_update_time >", value, "chatGroupUserUpdateTime");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("chat_group_user_update_time >=", value, "chatGroupUserUpdateTime");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserUpdateTimeLessThan(Date value) {
            addCriterion("chat_group_user_update_time <", value, "chatGroupUserUpdateTime");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("chat_group_user_update_time <=", value, "chatGroupUserUpdateTime");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserUpdateTimeIn(List<Date> values) {
            addCriterion("chat_group_user_update_time in", values, "chatGroupUserUpdateTime");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserUpdateTimeNotIn(List<Date> values) {
            addCriterion("chat_group_user_update_time not in", values, "chatGroupUserUpdateTime");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("chat_group_user_update_time between", value1, value2, "chatGroupUserUpdateTime");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("chat_group_user_update_time not between", value1, value2, "chatGroupUserUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserIdLikeInsensitive(String value) {
            addCriterion("upper(user_id) like", value.toUpperCase(), "userId");
            return (Criteria) this;
        }

        public Criteria andChatGroupIdLikeInsensitive(String value) {
            addCriterion("upper(chat_group_id) like", value.toUpperCase(), "chatGroupId");
            return (Criteria) this;
        }

        public Criteria andChatGroupUserRealNameLikeInsensitive(String value) {
            addCriterion("upper(chat_group_user_real_name) like", value.toUpperCase(), "chatGroupUserRealName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chat_group_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}