package dao.model.base;

import java.io.Serializable;
import java.util.Date;

public class ChatGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group.chat_group_id
     *
     * @mbg.generated
     */
    private String chatGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group.chat_group_name
     *
     * @mbg.generated
     */
    private String chatGroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group.chat_group_create_time
     *
     * @mbg.generated
     */
    private Date chatGroupCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group.user_group_id
     *
     * @mbg.generated
     */
    private String userGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group.chat_group_id
     *
     * @return the value of chat_group.chat_group_id
     *
     * @mbg.generated
     */
    public String getChatGroupId() {
        return chatGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group.chat_group_id
     *
     * @param chatGroupId the value for chat_group.chat_group_id
     *
     * @mbg.generated
     */
    public void setChatGroupId(String chatGroupId) {
        this.chatGroupId = chatGroupId == null ? null : chatGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group.chat_group_name
     *
     * @return the value of chat_group.chat_group_name
     *
     * @mbg.generated
     */
    public String getChatGroupName() {
        return chatGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group.chat_group_name
     *
     * @param chatGroupName the value for chat_group.chat_group_name
     *
     * @mbg.generated
     */
    public void setChatGroupName(String chatGroupName) {
        this.chatGroupName = chatGroupName == null ? null : chatGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group.chat_group_create_time
     *
     * @return the value of chat_group.chat_group_create_time
     *
     * @mbg.generated
     */
    public Date getChatGroupCreateTime() {
        return chatGroupCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group.chat_group_create_time
     *
     * @param chatGroupCreateTime the value for chat_group.chat_group_create_time
     *
     * @mbg.generated
     */
    public void setChatGroupCreateTime(Date chatGroupCreateTime) {
        this.chatGroupCreateTime = chatGroupCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group.user_group_id
     *
     * @return the value of chat_group.user_group_id
     *
     * @mbg.generated
     */
    public String getUserGroupId() {
        return userGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group.user_group_id
     *
     * @param userGroupId the value for chat_group.user_group_id
     *
     * @mbg.generated
     */
    public void setUserGroupId(String userGroupId) {
        this.userGroupId = userGroupId == null ? null : userGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChatGroup other = (ChatGroup) that;
        return (this.getChatGroupId() == null ? other.getChatGroupId() == null : this.getChatGroupId().equals(other.getChatGroupId()))
            && (this.getChatGroupName() == null ? other.getChatGroupName() == null : this.getChatGroupName().equals(other.getChatGroupName()))
            && (this.getChatGroupCreateTime() == null ? other.getChatGroupCreateTime() == null : this.getChatGroupCreateTime().equals(other.getChatGroupCreateTime()))
            && (this.getUserGroupId() == null ? other.getUserGroupId() == null : this.getUserGroupId().equals(other.getUserGroupId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChatGroupId() == null) ? 0 : getChatGroupId().hashCode());
        result = prime * result + ((getChatGroupName() == null) ? 0 : getChatGroupName().hashCode());
        result = prime * result + ((getChatGroupCreateTime() == null) ? 0 : getChatGroupCreateTime().hashCode());
        result = prime * result + ((getUserGroupId() == null) ? 0 : getUserGroupId().hashCode());
        return result;
    }
}