package dao.dao.base;

import dao.model.base.ChatGroupUser;
import dao.model.base.ChatGroupUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatGroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    long countByExample(ChatGroupUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    int deleteByExample(ChatGroupUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    int insert(ChatGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    int insertSelective(ChatGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    List<ChatGroupUser> selectByExample(ChatGroupUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatGroupUser record, @Param("example") ChatGroupUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatGroupUser record, @Param("example") ChatGroupUserCriteria example);
}