package dao.dao.base;

import dao.model.base.Chat;
import dao.model.base.ChatCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    long countByExample(ChatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    int deleteByExample(ChatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String chatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    int insert(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    int insertSelective(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    List<Chat> selectByExample(ChatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    Chat selectByPrimaryKey(String chatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Chat record, @Param("example") ChatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Chat record, @Param("example") ChatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Chat record);
}